//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp111
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        public Customers()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int CustomerID { get; set; }
        public string Name { get; set; }
        public string Inn { get; set; }
        public string Adress { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> Salesman { get; set; }
        public Nullable<bool> Buyer { get; set; }
    
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
