//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp111
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialID
    {
        public MaterialID()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int MaterialID1 { get; set; }
        public string Name { get; set; }
        public Nullable<int> Price { get; set; }
        public string Units { get; set; }
    
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
