//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp111
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.OrderDetails = new HashSet<OrderDetails>();
            this.Specifications = new HashSet<Specifications>();
        }
    
        public int ProductID { get; set; }
        public string Name { get; set; }
        public string Units { get; set; }
    
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
        public virtual ICollection<Specifications> Specifications { get; set; }
    }
}
