//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp111
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specifications
    {
        public int SpecificationID { get; set; }
        public string Name { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> MaterialID { get; set; }
        public string Quantity { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
